src/apps/libros/urls.py
from django.conf.urls import url
from apps.libros import views

urlpatterns = [

    url(r'^inicio/', views.inicio, name='inicio'),
    url(r'^crear/', views.crear, name='crear'),
    url(r'^actualizar/', views.actualizar, name='actualizar'),
    url(r'^borrar/', views.borrar, name='borrar'),
]

src/biblioteca/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^libros/', include('apps.libros.urls', namespace='libros')),
]

src/apps/libros/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Autor(models.Model):
    nombre = models.CharField(max_length=50)
    ciudad = models.CharField(max_length=50)
    genero = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Libro(models.Model):
    autor = models.ForeignKey(Autor)
    nombre = models.CharField(max_length=50)
    categoria = models.CharField(max_length=50)
    idioma = models.CharField(max_length=50)

    def __str__(self):
       return self.nombre

src/apps/libros/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.


def inicio (request):
    return render(request, 'libros/index.html')


def crear (request):
    return render(request, 'libros/crear.html')


def actualizar (request):
    return render(request, 'libros/actualizar.html')


def borrar (request):
    return render(request, 'libros/borrar.html')

src/templates/base.html
<!doctype html>
    {% load static%}
<html lang="en">
<head>
    <!--<link rel="stylesheet" href=" {% static 'bootstrap.min.css'%}"> -->
  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Dashboard</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href={%static "/bower_components/bootstrap/dist/css/bootstrap.min.css"%}>
  <!-- Font Awesome -->
  <link rel="stylesheet" href={%static "/bower_components/font-awesome/css/font-awesome.min.css"%}>
  <!-- Ionicons -->
  <link rel="stylesheet" href={%static "/bower_components/Ionicons/css/ionicons.min.css"%}>
  <!-- jvectormap -->
  <link rel="stylesheet" href={%static "/bower_components/jvectormap/jquery-jvectormap.css"%}>
  <!-- Theme style -->
  <link rel="stylesheet" href={%static "dist/css/AdminLTE.min.css"%}>
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href={%static "/dist/css/skins/_all-skins.min.css"%}>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'libros:inicio' %}">Inicio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'libros:crear' %}">Crear<span class="sr-only">(current)</span></a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'libros:actualizar' %}">Actualizar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'libros:borrar' %}">Borrar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block contenido %}
{% endblock %}

</body>
<footer> <h6>Pedro Castilla Hurtado</h6>
         <h6>Desarrollador Web</h6>
            Copyright no se copie, trabaje
</footer>
</html>

src/templates/libros/actualizar.html
{% extends 'base.html'%}
#{% block contenido %}
<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Actualizar Libro</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Nombre</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="Ingrese Aqui..." class="form-control input-md" required="">
  <span class="help-block"></span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="categoria">Categoria</label>
  <div class="col-md-4">
  <input id="categoria" name="categoria" type="text" placeholder="Ingrese aqui" class="form-control input-md" required="">
  <span class="help-block"></span>
  </div>
</div>

<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Nombre autor">Autor</label>
  <div class="col-md-4">
    <select id="Nombre autor" name="Nombre autor" class="form-control">
      <option value="1">Option one</option>
      <option value="2">Option two</option>
    </select>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="guardar"></label>
  <div class="col-md-4">
    <button id="guardar" name="guardar" class="btn btn-primary">Guardar</button>
  </div>
</div>

</fieldset>
</form>
{% endblock %}

src/templates/libros/borrar.html
{% extends 'base.html'%}
#{% block contenido %}
<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Borrar Libro</legend>
    <!-- Button -->
    <h2>Esto es para BORRAR</h2>
</fieldset>
</form>
{% endblock %}

src/templates/libros/crear.html
{% extends 'base.html'%}
#{% block contenido %}
<form class="form-horizontal">
<fieldset>

<!-- Form Name -->
<legend>Crear Libro</legend>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="textinput">Nombre</label>
  <div class="col-md-4">
  <input id="textinput" name="textinput" type="text" placeholder="Ingrese Aqui..." class="form-control input-md" required="">
  <span class="help-block"></span>
  </div>
</div>

<!-- Text input-->
<div class="form-group">
  <label class="col-md-4 control-label" for="categoria">Categoria</label>
  <div class="col-md-4">
  <input id="categoria" name="categoria" type="text" placeholder="Ingrese aqui" class="form-control input-md" required="">
  <span class="help-block"></span>
  </div>
</div>

<!-- Select Basic -->
<div class="form-group">
  <label class="col-md-4 control-label" for="Nombre autor">Autor</label>
  <div class="col-md-4">
    <select id="Nombre autor" name="Nombre autor" class="form-control">
      <option value="1">Option one</option>
      <option value="2">Option two</option>
    </select>
  </div>
</div>

<!-- Button -->
<div class="form-group">
  <label class="col-md-4 control-label" for="guardar"></label>
  <div class="col-md-4">
    <button id="guardar" name="guardar" class="btn btn-primary">Guardar</button>
  </div>
</div>

</fieldset>
</form>
{% endblock %}

src/templates/libros/index.html
{% extends 'base.html'%}
{% block contenido %}
<div class="jumbotron">
  <h1 class="display-3">SOY PROGRAMADOR WEB, PA LAS QUE SEA</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="https://docs.djangoproject.com/es/1.11/intro/" role="button">Aprende conmigo</a>
  </p>
</div>
{% endblock %}